version: '2'
services:
  nginx:
    restart: always
    image: gurosh/frontend/nginx
    container_name: gurosh-frontend-nginx
    build: docker/nginx
    ports:
      - "8010:80"
    volumes:
      - ./docker/npm/src:/src
    env_file:
      - .env
    networks:
      docker0:
        external: true
        ipv4_address: 172.17.0.2

  npm:
    image: gurosh/frontend/npm
    container_name: gurosh-frontend-npm
    build: docker/npm
    volumes:
      - ./docker/npm/src:/src
    env_file:
      - .env
    networks:
      docker0:
        external: true
        ipv4_address: 172.17.0.3